use_frameworks!

target 'CCPriceLabel_Example' do
  pod 'CCPriceLabel', :path => '../'

  target 'CCPriceLabel_Tests' do
    inherit! :search_paths

      pod 'Quick', '~>  1.0'
      pod 'Nimble', '~> 5.0'
      #pod 'FBSnapshotTestCase'
      #pod 'Nimble-Snapshots'
  end
end
